vouchers:
  money:
    id: "STONE"
    name: "&b$10,000 For you my friend!"
    lore:
      - 'You can add a lore!'
    commands:
      - 'eco give {player} 10000'
menus:
  admin-menu:
    name: "&cVouchers Admin"